<h1 class="w3-container">About</h1>


<section class="w3-container">
    <h2>WatchTV</h2>
    <p>WatchTV is made with almost pure php. The only non PHP parts is the DVBV5-ZAP client.</p>
    <p><a href="https://github.com/phpbg/watchtv">Homepage</a></p>
    <p><a href="https://github.com/phpbg/watchtv/blob/master/readme.md">Manual</a></p>
    <p><a href="https://github.com/phpbg/watchtv/releases">Releases</a></p>
</section>


<section class="w3-container">
    <h2>Awesome librairies</h2>
    <p><a href="https://linuxtv.org/wiki/index.php/Dvbv5-zap">DVBV5-ZAP</a>: the official DVB command line tuning tool</p>
    <p><a href="https://github.com/lightful/DVBdirect">DVBJET</a>: a simple and straightforward command line tuning tool</p>
    <p><a href="https://github.com/phpbg/mini-httpd">Mini HTTPD</a>: a mini framework build upon <a href="https://github.com/reactphp/http">React PHP HTTP server</a></p>
    <p><a href="https://github.com/reactphp">React PHP</a>: Event-driven, non-blocking I/O with PHP</p>
    <p><a href="https://github.com/phpbg/rtsp">RTSP1/0 server</a></p>
    <p><a href="https://github.com/phpbg/dvbpsi">DVBPSI</a>: parse MPEG-TS DVB PSI tables</p>
</section>


<section class="w3-container">
    <h2>License</h2>
    MIT License

    Copyright (c) 2019 Samuel CHEMLA

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
</section>