<div id="app">
    <div class="w3-container">
        <h1 class="w3-center">Guide</h1>
        <div v-if="! showEpg">Please wait...</div>
        <div v-if="showEpg" class="epgAndChannelContainer bordered">
            <div>
                <div class="commonHeight bordered"></div>
                <div class="commonHeight bordered"></div>
                <div v-for="(channel, channelIdx) in orderedChannels" class="commonHeight bordered">
                    {{channel["NAME"]}}
                </div>
            </div>
            <div ref="epgContainer" class="epgContainer noselect" v-on:mousedown="dragStart" v-on:mousemove="drag" v-on:mouseup="dragStop" :style="computeContainerStyle()">
                <div class="days commonHeight">
                    <div class="dayStep commonHeight bordered" v-for="dayTimestamp in days" :style="computeStyleFromDayStep(dayTimestamp)">{{dayTimestamp | toDay}}</div>
                </div>
                <div class="hours commonHeight">
                    <div class="hourStep commonHeight bordered" v-for="hourTimestamp in hours" :style="computeStyleFromHourStep(hourTimestamp)">{{hourTimestamp | toHour}}</div>
                </div>
                <div class="channel commonHeight" v-for="(channel, channelIdx) in orderedChannels">
                    <div class="event w3-hover-green commonHeight bordered" v-for="event in getEventsForChannel(channel)" :style="computeStyleFromEPGEvent(event)" :title="getEitShortText(event)">{{getEitName(event)}}</div>
                </div>
                <div class="nowLine" :style="computeNowLineStyle()"></div>
            </div>
        </div>
    </div>
</div>