<div id="app" v-cloak>
    <div class="w3-container">
        <h1 class="w3-center">Guide</h1>
        <div v-if="! showEpg">Please wait...</div>
        <div v-if="showEpg" class="epgAndChannelContainer bordered">
            <div class="channelNames bordered">
                <div class="commonHeight bordered"></div>
                <div class="commonHeight bordered"></div>
                <div v-for="channel in orderedChannels" class="commonHeight bordered striped">
                    {{channel["NAME"]}}
                </div>
            </div>
            <div ref="epgContainer" class="epgContainer noselect" v-on:mousedown="dragStart" v-on:mousemove="drag" v-on:mouseup="dragStop" v-on:mouseleave="dragStop" :style="containerStyle">
                <div class="days commonHeight">
                    <div class="dayStep commonHeight bordered" v-for="day in daysWithStyle" :style="day.style">{{day.timestamp | toDay}}</div>
                </div>
                <div class="hours commonHeight">
                    <div class="hourStep commonHeight bordered" v-for="hour in hoursWithStyle" :style="hour.style">{{hour.timestamp | toHour}}</div>
                </div>
                <div class="channel commonHeight childStriped" v-for="channel in orderedChannels">
                    <div class="event w3-hover-green commonHeight bordered" v-for="event in eventsByChannel[channel.SERVICE_ID]" @click="selectEvent(event)" :style="event._style">{{getEitName(event)}}</div>
                </div>
                <div class="nowLine" :style="nowLineStyle"></div>
            </div>
        </div>
    </div>

    <modal v-if="eventSelected" @close="eventSelected = null">
        <div slot="header">
            {{getEitName(eventSelected)}}
        </div>
        <div slot="body" >
            <p>
                <b>{{ getChannelName(eventSelected) }}</b>
                <br>
                {{ eventSelected.startTimestamp | toDatetime }}, {{eventSelected.duration | toDurationMin}}min
                <br>
                {{ getCategory(eventSelected) }}
            </p>
            <p>{{getEitShortText(eventSelected)}}</p>
        </div>
    </modal>

</div>

<script type="text/x-template" id="modal-template">
    <transition name="modal">
        <div class="modal-mask">
            <div class="modal-wrapper" @click="$emit('close')">
                <div class="modal-container" @click.stop="" role="dialog" aria-modal="true" aria-label="Modal" @keyup.esc="$emit('close')" tabindex="0">
                    <div class="modal-header">
                        <slot name="header">
                        </slot>
                    </div>

                    <div class="modal-body">
                        <slot name="body">
                        </slot>
                    </div>

                    <div class="modal-footer">
                        <button @click="$emit('close')" title="Close" aria-label="Close">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </transition>
</script>