<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Watch TV</title>
    <?php
    if (!empty($this->bottomScripts)) {
        foreach ($this->bottomScripts as $src) {
            echo "<link rel='preload' href='{$src}' as='script'>";
        }
    }
    if (!empty($this->headCss)) {
        foreach ($this->headCss as $src) {
            echo "<link rel='stylesheet' type='text/css' href='{$src}'>";
        }
    }
    if (!empty($this->inlineCss)) {
        foreach ($this->inlineCss as $css) {
            echo "<style>{$css}</style>";
        }
    }
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        nav ul {
            padding: 0px;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }
    </style>
</head>
<body>

<?php echo $this->content; ?>

<nav class="w3-container">
    <ul class="w3-bar">
        <li class="w3-bar-item w3-mobile"><a href="/">Home</a></li>
        <li class="w3-bar-item w3-mobile"><a href="/epg-html">Guide</a></li>
        <li class="w3-bar-item w3-mobile"><a href="/channels/m3u8">Download M3U</a></li>
        <li class="w3-bar-item w3-mobile"><a href="/epg">Download EPG</a></li>
        <li class="w3-bar-item w3-mobile"><a href="/configure">Configure</a></li>
        <li class="w3-bar-item w3-mobile"><a href="/about">About</a></li>
    </ul>
</nav>

<?php

if (!empty($this->bottomScripts)) {
    foreach ($this->bottomScripts as $src) {
        echo "<script src='{$src}'></script>";
    }
}

if (!empty($this->inlineScripts)) {
    foreach ($this->inlineScripts as $script) {
        echo "<script>{$script}</script>";
    }
}

?>

</body>
</html>